services:
  - type: web
    name: kitkat-universe
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false