services:
  - type: web
    name: kitkat-universe
    env: elixir
    # rootDir: . # Uncomment and set if mix.exs is in a subdirectory
    buildCommand: mix deps.get --only prod && mix compile && mix assets.deploy
    startCommand: mix phx.server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST